#!/usr/bin/env python3
"""Canonical 36 pairs: 28 cross-model (i<j) + 8 self-to-self pairs."""
from __future__ import annotations

import argparse
from itertools import combinations
from pathlib import Path

MODELS = sorted(
    [
        "allenai_OLMo-3-7B-Instruct",
        "DeepSeek-R1-Distill-Llama-8B",
        "Meta-Llama-3-8B-Instruct",
        "Mistral-7B-Instruct-v0.2",
        "Mistral-7B-Instruct-v0.3",
        "Qwen2.5-7B-Instruct",
        "Qwen3-8B",
        "Qwen_Qwen3-14B",
    ],
    key=str.lower,
)


def pairs_cross():
    return list(combinations(MODELS, 2))


def pairs_self():
    return [(m, m) for m in MODELS]


def pairs_all():
    return pairs_cross() + pairs_self()


def main() -> None:
    p = argparse.ArgumentParser()
    p.add_argument("--bash-export", action="store_true")
    p.add_argument("--cross-only", action="store_true",
                   help="Only emit the 36 cross-model pairs (no self-pairs).")
    args = p.parse_args()
    pairs = pairs_cross() if args.cross_only else pairs_all()
    if args.bash_export:
        print(f"# Generated by scripts/list_false_belief_pairs.py --bash-export ({len(pairs)} pairs)")
        print("MODEL_1=(")
        for a, _ in pairs:
            print(f"  '{a}'")
        print(")")
        print("MODEL_2=(")
        for _, b in pairs:
            print(f"  '{b}'")
        print(")")
        return
    for i, (a, b) in enumerate(pairs):
        tag = " (self)" if a == b else ""
        print(f"{i:2d}  {a}  x  {b}{tag}")


if __name__ == "__main__":
    main()
